name: Waka Readme

on:
  schedule:
    # 国际标准时间下午 16 点，北京时间晚上 0 点
    - cron: '0 16 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: YLRK/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LANGUAGE_PER_REPO: False
          SHOW_DAYS_OF_WEEK: False
          SHOW_COMMIT: False
          SHOW_LOC_CHART: False
          SHOW_PROJECTS: False
          SHOW_SHORT_INFO: False
          SHOW_PROFILE_VIEWS: False
          SHOW_TOTAL_CODE_TIME: False
          SHOW_UPDATED_DATE: False
          SYMBOL_VERSION: 3
      - name: generate github-contribution-grid-snake.svg
        uses: YLRK/snk/svg-only@v2
        with:
          github_user_name: ylrk
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
