name: Waka Readme

on:
  schedule:
    # 国际标准时间下午 16 点，北京时间晚上 0 点
    - cron: '0 16 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: YLRK/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LANGUAGE_PER_REPO: False
          SHOW_DAYS_OF_WEEK: False
          SHOW_COMMIT: False
          SHOW_LOC_CHART: False
          SHOW_PROJECTS: False
          SHOW_SHORT_INFO: False
          SHOW_PROFILE_VIEWS: False
          SHOW_TOTAL_CODE_TIME: False
          SHOW_UPDATED_DATE: False
          SYMBOL_VERSION: 3
