name: Waka Readme

on:
  schedule:
    # 国际标准时间下午 16 点，北京时间晚上 0 点
    - cron: '0 16 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: YLRK/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LANGUAGE_PER_REPO: False
          SHOW_DAYS_OF_WEEK: False
          SHOW_COMMIT: False
          SHOW_LOC_CHART: False
          SHOW_PROJECTS: False
          SHOW_SHORT_INFO: False
          SHOW_PROFILE_VIEWS: False
          SHOW_TOTAL_CODE_TIME: False
          SHOW_UPDATED_DATE: False
          SYMBOL_VERSION: 3
      - uses: Platane/snk@master
        with:
          # github user name to read the contribution graph from (**required**)
          # using action context var `github.repository_owner` or specified user
          github_user_name: ylrk

          # list of files to generate.
          # one file per line. Each output can be customized with options as query string.
          #
          #  supported options:
          #  - palette:     A preset of color, one of [github, github-dark, github-light]
          #  - color_snake: Color of the snake
          #  - color_dots:  Coma separated list of dots color.
          #                 The first one is 0 contribution, then it goes from the low contribution to the highest.
          #                 Exactly 5 colors are expected.
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
